version: '3.9'

services:
  appservicios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appservicios
    ports:
      - "7293:7293"  # HTTPS
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgresql;Port=5432;Database=basket;Username=sa;Password=yourStrong#Password"
    networks:
      - servicios-network

networks:
  servicios-network:
    external: true